spring:
  application:
    name: ms-user-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
    ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/user
    username: foo
    password: bar
#    driverClassName: org.postgresql.Driver