management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port : 8081
  servlet:
    context-path: /ms-user-service
#hostname: ms-user-service:8081
spring:
  application:
    name: ms-user-service
  flyway:
    enabled: true
    baseline-on-migrate : true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
#      This config will override the flyway because it will drop the user schema flyway
#      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/ms_user_service
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  data:
    redis:
      host: localhost
      user:
      password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      port: '6379'
      database: '0'
      timeout: '60000'

rabbitmq:
  internal-mail:
    exchanges: internal.exchange
    routing-keys: internal.mail.routing-key

jwt:
  secret: 208bc47b3e1ee5554e388c735b9f234f89ac246e8ce463c8313fc1cff16e760e

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${EUREKA_HOST:localhost}