server:
  port : 8000
spring:
  application:
    name: ms-api-gateway
  main:
    web-application-type: reactive
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      globalcors:
        corsConfigurations:
          '[/ui/v1/**]':
            allowedOrigins: "http://localhost:3000"
            exposedHeaders: "page-total-count"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
              - HEAD
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        -   id: ms-user-service
            uri: lb://ms-user-service
            predicates:
              - Path=/ui/v1/user/**, /api/v1/user/**, /api/v1/auth/**
            filters:
              - name: AuthFilter

#        Do not apply filter for this route
        -   id: ms-user-service-auth
            uri: lb://ms-user-service
            predicates:
              - Path=/ui/v1/auth/**
            filters:
              - RewritePath=/ui/v1/auth/(?<segment>.*), /ms-user-service/ui/v1/auth/$\{segment}

        -   id: email-service
            uri: lb://email-service
            predicates:
              - Path=/api/v1/email/suggested

#  zipkin:
#    base-url: http://${ZIPKIN_HOST:localhost}:9411

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${EUREKA_HOST:localhost}