server:
  port : 8081
rabbitmq:
  internal-mail:
    exchanges: internal.exchange
    listener:
      queue-name: email-queue
    routing-key: internal.mail.routing-key

spring:
  mail:
    host: smtp.gmail.com
    username: walkerelot16@gmail.com
    password: 'jhyb dxbj teez hwjq'
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
